module.exports = {
  extends: ["stylelint-config-standard", "stylelint-stylistic/config"],
  overrides: [
    {
      files: ["*.css", "**/*.css"],
    },
  ],
  rules: {
    "alpha-value-notation": "percentage",
    "annotation-no-unknown": true,
    "at-rule-no-unknown": null,
    "at-rule-no-vendor-prefix": true,
    "block-no-empty": true,
    "color-hex-length": "short",
    "color-no-invalid-hex": true,
    "color-function-notation": "modern",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    "custom-property-no-missing-var-function": true,
    "declaration-property-value-no-unknown": null,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-no-important": true,
    "font-family-no-duplicate-names": true,
    "font-weight-notation": "numeric",
    "font-family-name-quotes": "always-unless-keyword",
    "function-no-unknown": [
      true,
      {
        ignoreFunctions: ["theme"],
      },
    ],
    "function-name-case": "lower",
    "function-url-quotes": "always",
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "hue-degree-notation": "angle",
    "import-notation": "string",
    "length-zero-no-unit": true,
    "keyframe-selector-notation": "percentage-unless-within-keyword-only-block",
    "keyframe-block-no-duplicate-selectors": true,
    "keyframe-declaration-no-important": true,
    "media-feature-name-no-unknown": true,
    "media-feature-name-value-no-unknown": true,
    "media-feature-range-notation": "context",
    "media-feature-name-no-vendor-prefix": true,
    "media-query-no-invalid": true,
    "number-max-precision": 3,
    "number-leading-zero": "never",
    "no-descending-specificity": null,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-invalid-position-at-import-rule": true,
    "no-unknown-animations": true,
    "no-unknown-custom-properties": true,
    "no-invalid-double-slash-comments": true,
    "property-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "selector-no-vendor-prefix": true,
    "selector-class-pattern": null,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "selector-type-case": "lower",
    "selector-pseudo-element-colon-notation": "double",
    "selector-attribute-quotes": "always",
    "unit-no-unknown": null,
    "value-keyword-case": null,
    "value-no-vendor-prefix": true,
  },
};
